title: Jetti Yaswanth
#logo: \add path
email: jetti.yaswanth18@gmail.com
description:>- Passionate about leveraging cutting-edge technology to revolutionize human thought processes.
show_downloads: True
twitter_username: jekyllrb
github_username:  jekyll
google Scholor: "https://scholar.google.com/citations?user=wFbVtPMAAAAJ&hl=en"
theme: jekyll-theme-minimal

# Build settings
#theme: minima
#plugins:
# - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
